In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
import torch
import re
from sklearn.metrics import balanced_accuracy_score, roc_auc_score,accuracy_score,precision_recall_fscore_support
from Constants import *
from Preprocessing import *
from Models import *
import copy
from Utils import *
from DeepSurvivalModels import *
pd.set_option('display.max_rows', 200)



In [3]:
rad_data = DTDataset(use_smote=False)
control_data = DTDataset(radiomics_cluster_file=None,
                 radiomics_embedding_file=None)
rad_data.processed_df.T

/home/awentze2/git_repos/DigitalTwinVis/python/Preprocessing.py:186: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dummy_df = pd.get_dummies(df[to_onehot].fillna(0).astype(str),drop_first=False)
/home/awentze2/git_repos/DigitalTwinVis/python/Preprocessing.py:294: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  processed_df = preprocess_dt_data(df,self.ln_cols).fillna(0).drop(['DLT_Type'],axis=1)
/home/awentze2/git_repos/DigitalTwinVis/python/Preprocessing.py:186: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and wi

id,3,5,6,7,8,9,10,11,13,14,...,10196,10197,10198,10199,10200,10201,10202,10203,10204,10205
hpv,1,0,1,1,1,1,-1,1,0,1,...,0,1,-1,0,1,1,0,1,0,1
age,55.969444,20.95,69.930556,72.319444,59.730556,60.083333,67.708333,57.858333,51.758333,56.25,...,47.619444,50.163889,70.888889,67.825,56.336111,49.566667,48.705556,77.116667,45.95,49.733333
packs_per_year,0.0,38.0,35.0,0.0,0.0,0.0,40.0,44.0,0.0,40.0,...,5.0,0.0,50.0,0.0,0.0,30.0,30.0,0.0,5.0,0.0
gender,1,1,0,1,1,1,1,1,1,1,...,0,1,0,1,1,1,1,1,1,1
Aspiration rate Pre-therapy,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
total_dose,66.0,72.0,70.0,70.0,66.0,66.0,69.96,70.0,70.0,70.0,...,70.0,72.0,66.0,70.0,69.96,70.0,72.0,70.0,69.96,69.96
dose_fraction,2.2,1.8,2.121212,2.121212,2.2,2.2,2.12,2.121212,2.0,2.121212,...,2.121212,1.8,2.2,2.121212,2.12,2.121212,1.714286,2.333333,2.12,2.12
OS (Calculated),6.033333,7.333333,7.466667,7.8,8.066667,8.733333,9.1,9.8,10.033333,10.033333,...,139.033333,139.3,140.6,142.833333,143.033333,143.2,144.366667,148.366667,152.6,155.533333
Locoregional control (Time),4.7,7.333333,7.466667,7.8,8.066667,8.733333,6.7,8.5,10.033333,10.033333,...,139.033333,139.3,140.6,142.833333,143.033333,143.2,144.366667,148.366667,152.6,155.533333
FDM (months),6.033333,7.333333,7.466667,7.8,8.066667,6.633333,9.1,9.8,10.033333,10.033333,...,139.033333,139.3,140.6,142.833333,143.033333,143.2,144.366667,136.033333,152.6,155.533333


In [19]:
rad_model1,rad_model2,rad_model3,rad_smodel3 = load_transition_models('radcluster_')
rad_model1

BayesianOutcomeSimulator(
  (input_dropout): Dropout(p=0.1, inplace=False)
  (layers): ModuleList(
    (0): Linear(in_features=69, out_features=500, bias=True)
    (1): ReLU()
    (2): Linear(in_features=500, out_features=500, bias=True)
    (3): ReLU()
  )
  (batchnorm): BatchNorm1d(500, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (dropout): Dropout(p=0.5, inplace=False)
  (relu): Softplus(beta=1.0, threshold=20.0)
  (sigmoid): Sigmoid()
  (softmax): Softmax(dim=1)
  (disease_layer): Linear(in_features=501, out_features=3, bias=True)
  (nodal_disease_layer): Linear(in_features=501, out_features=3, bias=True)
  (dlt_layers): ModuleList(
    (0-4): 5 x Linear(in_features=501, out_features=1, bias=True)
  )
  (treatment_layer): Linear(in_features=501, out_features=6, bias=True)
)

In [20]:
control_model1,control_model2,control_model3,control_smodel3 = load_transition_models('control_')
control_model1

BayesianOutcomeSimulator(
  (input_dropout): Dropout(p=0.1, inplace=False)
  (layers): ModuleList(
    (0): Linear(in_features=61, out_features=500, bias=True)
    (1): ReLU()
    (2): Linear(in_features=500, out_features=500, bias=True)
    (3): ReLU()
  )
  (batchnorm): BatchNorm1d(500, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (dropout): Dropout(p=0.5, inplace=False)
  (relu): Softplus(beta=1.0, threshold=20.0)
  (sigmoid): Sigmoid()
  (softmax): Softmax(dim=1)
  (disease_layer): Linear(in_features=501, out_features=3, bias=True)
  (nodal_disease_layer): Linear(in_features=501, out_features=3, bias=True)
  (dlt_layers): ModuleList(
    (0-4): 5 x Linear(in_features=501, out_features=1, bias=True)
  )
  (treatment_layer): Linear(in_features=501, out_features=6, bias=True)
)

In [21]:
def temporal_loss(timestoevents,weights=None,maxtime=48,threshold=True):
    #list of expected times to events, usualy in order of Const.temporal_outcomes
    #basically longer = better, we count > maxtime (weeks) as no event
    if weights is None: 
        weights = [1 for i in range(len(timestoevents))]
    scores =  [(w*maxtime/t)for w,t in zip(weights,timestoevents)]
    if threshold:
        scores = [s*torch.lt(t,maxtime) for s,t in zip(scores,timestoevents)]
    scores = torch.stack(scores).sum(axis=0)
    return scores

def outcome_loss(ypred,weights=None):
    #default weights is bad
    if weights is None: 
        print('using default outcome loss weights, which is probably wrong since bad stuff should be negative')
        weights = [1 for i in range(ypred.shape[1])]
    l = torch.mul(ypred[:,0],weights[0])
    for i,weight in enumerate(weights[1:]):
        #weights with negative values will invert the outcome so e.g. Regional control becomes no regional control
        #so the penaly is correct
        newloss = torch.mul(ypred[:,i+1],weight)
        l = torch.add(l,newloss)
    return l

def calc_optimal_decisions(dataset,ids,m1,m2,m3,sm3,
                           weights=[0,0.5,.5,0], #weight for OS, FT, AS, and LRC as binary probabilities
                           tweights=[1,1,1,1], #weight for OS, LRC, FDM, and event (any + FT or AS at 6m) as time to event in weeks
                           outcome_loss_func=None,
                           threshold_temporal_loss = False,
                           maxtime=48,
                           get_transitions=True):
    m1.eval()
    m2.eval()
    m3.eval()
    sm3.eval()
    device = m1.get_device()
    data = dataset.processed_df.copy().loc[ids]
    
    def get_dlt(state):
        if state == 2:
            return data[Const.dlt2].copy()
        d = data[Const.dlt1].copy()
        if state < 1:
            d.values[:,:] = 0
        return d
    
    def get_pd(state):
        if state == 2:
            return data[Const.primary_disease_states2].copy()
        d = data[Const.primary_disease_states].copy()
        if state < 1:
            d.values[:,:] = 0
        return d
    
    def get_nd(state):
        if state == 2:
            return data[Const.nodal_disease_states2].copy()
        d = data[Const.nodal_disease_states].copy()
        if state < 1:
            d.values[:,:] = 0
        return d
    
    def get_cc(state):
        res = data[Const.ccs].copy()
        if state == 1:
            res.values[:,:] = np.zeros(res.values.shape)
        return res
    
    def get_mod(state):
        res = data[Const.modifications].copy()
        #this should have an ic condition but we don't use it anumore anywa
        return res
        
    def formatdf(d):
        d = df_to_torch(d).to(device)
        return d
    
    
    outcomedf = data[Const.outcomes]
    baseline = dataset.get_state('baseline').loc[ids]
    baseline_input = formatdf(baseline)

        
    if outcome_loss_func is None:
        outcome_loss_func = outcome_loss
    
    cat = lambda x: torch.cat([xx.to(device) for xx in x],axis=1).to(device)
    format_transition = lambda x: x.to(device)
    def get_outcome(d1,d2,d3):
        d1 = torch.full((len(ids),1),d1).type(torch.FloatTensor)
        d2 = torch.full((len(ids),1),d2).type(torch.FloatTensor)
        d3 = torch.full((len(ids),1),d3).type(torch.FloatTensor)
        
        tinput1 = cat([baseline_input,d1])
        ytransition = m1(tinput1)
        [ypd1,ynd1,ymod,ydlt1] = [format_transition(xx) for xx in ytransition['predictions']]
        d1_thresh = torch.gt(d1,.5).view(-1,1).to(device)
        ypd1[:,0:2] = ypd1[:,0:2]*d1_thresh
        ynd1[:,0:2] = ynd1[:,0:2]*d1_thresh
        
        tinput2 = cat([baseline_input,ypd1,ynd1,ymod,ydlt1,d1,d2])
        ytransition2 = m2(tinput2)
        [ypd2,ynd2,ycc,ydlt2] = [format_transition(xx) for xx in ytransition2['predictions']]
        
        input3 = cat([baseline_input, ypd2, ynd2, ycc, ydlt2, d1, d2,d3])
        outcome = m3(input3)['predictions']
        temporal_outcomes = sm3.time_to_event(input3,n_samples=1)
        
        transitions = {
            'pd1': ypd1,
            'nd1': ynd1,
            'nd2': ynd2,
            'pd2': ypd2,
            'mod': ymod,
            'cc': ycc,
            'dlt1': ydlt1,
            'dlt2': ydlt2,
        }
        return outcome, temporal_outcomes, transitions

    losses = []
    loss_order = []
    transitions = {}
    for d1 in [0,1]:
        for d2 in [0,1]:
            for d3 in [0,1]:
                outcomes, tte, transition_entry = get_outcome(d1,d2,d3)
                loss = outcome_loss_func(outcomes,weights)
                tloss = temporal_loss(tte,tweights,maxtime=maxtime,threshold=threshold_temporal_loss)
                loss += tloss
                losses.append(loss)
                loss_order.append([d1,d2,d3])
                transitions[str(d1)+str(d2)+str(d3)] = transition_entry
    losses = torch.stack(losses,axis=1)
    optimal_decisions = [loss_order[i] for i in torch.argmin(losses,axis=1)]
    result = torch.tensor(optimal_decisions).type(torch.FloatTensor)
    print(result.sum(axis=0),result.shape[0])
    if get_transitions:
        opt_transitions = {k: torch.zeros(v.shape).type(torch.FloatTensor) for k,v in transitions['000'].items()}
        for i,od in enumerate(optimal_decisions):
            key = ''.join([str(o) for o in od])
            entry = transitions[key]
            for kk,vv in entry.items():
                opt_transitions[kk][i,:] = vv[i,:]
        return result, opt_transitions
    return result

test, testtest = get_tt_split()
calc_optimal_decisions(rad_data,
                       testtest,rad_model1,rad_model2,rad_model3,rad_smodel3,
                       threshold_temporal_loss=False,
                       maxtime=48,
                       weights=[0,0,0,0],
                       tweights=[2,0.1,0,0],
                      )

tensor([15.,  0.,  0.]) 147


(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [1., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [1., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [1., 0., 0.],
         [0., 0., 0.],
         [1., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [1., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0

In [32]:
def get_unique_sequence(array):
    #converts a row of boolean values to a unique number e.g. [1,1,0] => 11, [0,0,1] => 100
    uniqueify = lambda r: torch.sum(torch.stack([i*(10**ii) for ii,i in enumerate(r)]))
    return torch_apply_along_axis(uniqueify,array)

def train_decision_model_triplet(
    tmodel1,
    tmodel2,
    tmodel3,
    smodel3,
    dataset = None,
    use_default_split=True,
    use_bagging_split=False,
    use_attention=True,
    lr=.001,
    epochs=10000,
    patience=5,
    weights=[0,.5,.5,0], #realtive weight of survival, feeding tube, aspiration, andl lrc
    tweights=[1,1,1,0], #weight for OS, LRC, FDM, and event (any + FT or AS at 6m) as time to event in weeks
    opt_weights=[1,1,1], #weights for policy model for optimal decisions
    imitation_weights=[.5,1,1],#weights of imitation decisions, because ic overtrains too quickly
    imitation_weight=1,
    reward_weight=1,
    imitation_triplet_weight=2,
    reward_triplet_weight = 2,
    shufflecol_chance = 0.2,
    split=.7,
    resample_training=False,
    save_path='../data/models/',
    file_suffix='',
    verbose=True,
    use_gpu=False,
    **model_kwargs,
):
    tmodel1.eval()
    tmodel2.eval()
    tmodel3.eval()

    train_ids, test_ids = get_tt_split(use_default_split=use_default_split,use_bagging_split=use_bagging_split,resample_training=resample_training)
    true_ids = train_ids + test_ids #for saving memory without upsampling
    if dataset is None:
        dataset = DTDataset()
    data = dataset.processed_df.copy()
    
    def get_dlt(state):
        if state == 2:
            return data[Const.dlt2].copy()
        d = data[Const.dlt1].copy()
        if state < 1:
            d.values[:,:] = 0
        return d
    
    def get_pd(state):
        if state == 2:
            return data[Const.primary_disease_states2].copy()
        d = data[Const.primary_disease_states].copy()
        if state < 1:
            d.values[:,:] = 0
        return d
    
    def get_nd(state):
        if state == 2:
            return data[Const.nodal_disease_states2].copy()
        d = data[Const.nodal_disease_states].copy()
        if state < 1:
            d.values[:,:] = 0
        return d
    
    def get_cc(state):
        res = data[Const.ccs].copy()
        if state == 1:
            res.values[:,:] = np.zeros(res.values.shape)
        return res
    
    def get_mod(state):
        res = data[Const.modifications].copy()
        #this should have an ic condition but we don't use it anumore anywa
        return res
        
    outcomedf = data[Const.outcomes]
    baseline = dataset.get_state('baseline')
    
    def formatdf(d,dids=train_ids):
        d = df_to_torch(d.loc[dids]).to(model.get_device())
        return d
    
    def makegrad(v):
        if not v.requires_grad:
            v.requires_grad=True
        return v
    
    if use_attention:
        model = DecisionAttentionModel(baseline.shape[1],**model_kwargs)
    else:
        model_kwargs = {k:v for k,v in model_kwargs.items() if 'attention' not in k and 'embed' not in k}
        model = DecisionModel(baseline.shape[1],**model_kwargs)
        
    device = 'cpu'
    if use_gpu and torch.cuda.is_available():
        device = 'cuda'
        
    model.set_device(device)

    tmodel1.set_device(device)
    tmodel2.set_device(device)
    tmodel3.set_device(device)
    smodel3.set_device(device)
    hashcode = str(hash(','.join([str(i) for i in train_ids])))
    
    save_file = save_path + 'model_' + model.identifier +'_hash' + hashcode + file_suffix + '.tar'
    model.fit_normalizer(df_to_torch(baseline.loc[train_ids]))
    optimizer = torch.optim.Adam(model.parameters(),lr=lr)
    
    
    optimal_train,transitions_train = calc_optimal_decisions(dataset,train_ids,tmodel1,tmodel2,tmodel3,smodel3,
                                           weights=weights,tweights=tweights,
                                          )
    optimal_test,transitions_test = calc_optimal_decisions(dataset,test_ids,tmodel1,tmodel2,tmodel3,smodel3,
                                          weights=weights,tweights=tweights,
                                         )
    optimal_train = optimal_train.to(model.get_device())
    optimal_test = optimal_test.to(model.get_device())
    mse = torch.nn.MSELoss()
    bce = torch.nn.BCELoss()
    
    def compare_decisions(d1,d2,d3,ids):
#         ypred = np.concatenate([dd.cpu().detach().numpy().reshape(-1,1) for dd in [d1,d2,d3]],axis=1)
        ytrue = df_to_torch(outcomedf.loc[ids])
        dloss = bce(d1.view(-1),ytrue[:,0])
        dloss += bce(d2.view(-1),ytrue[:,1])
        dloss += bce(d3,view(-1),ytrue[:,2])
        return dloss
        
    def remove_decisions(df):
        cols = [c for c in df.columns if c not in Const.decisions ]
        ddf = df[cols]
        return ddf
    
    makeinput = lambda step,dids: df_to_torch(remove_decisions(dataset.get_input_state(step=step,ids=dids)))
    threshold = lambda x: torch.gt(x,torch.rand(x.shape[0])).type(torch.FloatTensor)

    randchoice = lambda x: x[torch.randint(len(x),(1,))[0]]
    tloss_func = torch.nn.TripletMarginLoss()
    def get_tloss(row,step,yt,x,imitation=True):
        if yt[:,step].std() < .001:
            return torch.tensor([0]).to(device)
        positive_idx= torch.nonzero(yt[:,step] == yt[row,step])
        if len(positive_idx) <= 1:
            print('no losses','n positive',len(positive_idx),'yt',yt[row,step],'row',row,'step',step,'imitation',imitation,end='\r')
            return torch.tensor([0]).to(device)
        positive_idx = torch.stack([ii for ii in positive_idx if ii != row]).view(-1)
        negative_idx = torch.tensor([ii for ii in range(x.shape[0]) if ii not in positive_idx and ii != row])
        if len(positive_idx) < 1 or len(negative_idx) < 1:
            print('no losses','n positive',len(positive_idx),'n negative',len(negative_idx),'yt',yt[row,step],'row',row,'step',step,'imitation',imitation,end='\r')
            return torch.tensor([0]).to(device)
        positive = x[randchoice(positive_idx)]
        negative = x[randchoice(negative_idx)]
        anchor = x[row]
        if use_attention:
            [anchor_embedding,pos_embedding,neg_embedding] = [model.get_embedding(xx.view(1,-1),position=step,use_saved_memory=True) for xx in [anchor,positive,negative]]
        else:    
            [anchor_embedding,pos_embedding,neg_embedding] = [model.get_embedding(xx.view(1,-1),position=step,concatenate=False)[int(imitation)] for xx in [anchor,positive,negative]]
        tloss = tloss_func(anchor_embedding,pos_embedding,neg_embedding)
        return tloss
    #save the inputs from the whole dataset for future reference
    if use_attention:
        full_data = []
        for mstep in [0,1,2]:
            full_data_step = [baseline, get_dlt(min(mstep,1)),
                         get_dlt(mstep),get_pd(mstep),get_nd(mstep),get_cc(mstep),get_mod(mstep)]
            full_data_step = torch.cat([formatdf(fd,true_ids) for fd in full_data_step],axis=1)
            full_data.append(full_data_step)
        full_data = torch.stack(full_data)
        model.save_memory(full_data)
        print(full_data.shape)
        
    def step(train=True):
        if train:
            model.train(True)
            tmodel1.train(True)
            tmodel2.train(True)
            tmodel3.train(True)
            optimizer.zero_grad()
            ids = train_ids
            y_opt = makegrad(optimal_train)
            transition_dict = {k: torch.clone(v).detach() for k,v in transitions_train.items()}
        else:
            ids = test_ids
            model.eval()
            tmodel1.eval()
            tmodel2.eval()
            tmodel3.eval()
            y_opt = makegrad(optimal_test)
            print(y_opt.mean(axis=0))
            transition_dict = {k: torch.clone(v).detach() for k,v in transitions_test.items()}
        model.set_device(device)
        ytrain = df_to_torch(outcomedf.loc[ids]).to(device)
        #imitation losses and decision 1
        xxtrained = [baseline, get_dlt(0),get_dlt(0),get_pd(0),get_nd(0),get_cc(0),get_mod(0)]
        xxtrain = [formatdf(xx,ids) for xx in xxtrained]
        xxtrain = torch.cat(xxtrain,axis=1).to(device)
        o1 = model(xxtrain,position=0,use_saved_memory= (not train))
        decision1_imitation = o1[:,3]
        decision1_opt = o1[:,0]
    
        imitation_loss1 = bce(decision1_imitation,ytrain[:,0])
        imitation_loss1 = torch.mul(imitation_loss1,imitation_weights[0])
        opt_loss1 = bce(decision1_opt,y_opt[:,0])
        opt_loss1 = torch.mul(opt_loss1,opt_weights[0])
        
        x1_imitation = [baseline, get_dlt(1),get_dlt(0),get_pd(1),get_nd(1),get_cc(1),get_mod(1)]
        x1_imitation = [formatdf(xx1,ids) for xx1 in x1_imitation]
        x1_imitation = torch.cat(x1_imitation,axis=1).to(device)
        
        o2 = model(x1_imitation,position=1,use_saved_memory= (not train))
            
        decision2_imitation = o2[:,4]
            
        imitation_loss2 =  bce(decision2_imitation,ytrain[:,1])
        imitation_loss2 = torch.mul(imitation_loss2,imitation_weights[1])
        
        
        x2_imitation = [baseline, get_dlt(1),get_dlt(2),get_pd(2),get_nd(2),get_cc(2),get_mod(2)]
        
        x2_imitation = [formatdf(xx2,ids) for xx2 in x2_imitation]
        x2_imitation = torch.cat(x2_imitation,axis=1).to(device)
        
        
        o3 = model(x2_imitation,position=2,use_saved_memory= (not train))
        
        decision3_imitation = o3[:,5]
        
        imitation_loss3 = bce(decision3_imitation,ytrain[:,2])
        imitation_loss3 = torch.mul(imitation_loss3,imitation_weights[2])
        
        opt_input2 = [
            formatdf(baseline,ids), 
            transition_dict['dlt1'],
            formatdf(get_dlt(0),ids),
            transition_dict['pd1'],
            transition_dict['nd1'], 
            formatdf(get_cc(0),ids),
            transition_dict['mod']
                 ]
        opt_input2 = [o.to(device) for o in opt_input2]

        opt_input2 = torch.cat(opt_input2,axis=1).to(device)
        decision2_opt = model(opt_input2,position=1,use_saved_memory= (not train))[:,1]
        
        opt_loss2 = bce(decision2_opt,y_opt[:,1])
        opt_loss2 = torch.mul(opt_loss2,opt_weights[1])
        
        opt_input3 = [
            formatdf(baseline,ids),
            transition_dict['dlt1'],
            transition_dict['dlt2'],
            transition_dict['pd2'],
            transition_dict['nd2'],
            transition_dict['cc'],
            transition_dict['mod'],
        ]
        opt_input3 = [o.to(device) for o in opt_input3]
        opt_input3 = torch.cat(opt_input3,axis=1).to(device)
        decision3_opt = model(opt_input3,position=2,use_saved_memory= (not train))[:,2]
        
        opt_loss3 = bce(decision3_opt,y_opt[:,2])
        opt_loss3 = torch.mul(opt_loss3,opt_weights[2])
        
        iloss = torch.add(torch.add(imitation_loss1,imitation_loss2),imitation_loss3)
        iloss = torch.mul(iloss,imitation_weight)
        
        reward_loss = torch.add(torch.add(opt_loss1,opt_loss2),opt_loss3)
        reward_loss =torch.mul(reward_loss,reward_weight)
        
        loss = torch.add(iloss,reward_loss)
        
        imitation_tloss = torch.FloatTensor([0]).to(device)
        opt_tloss = torch.FloatTensor([0]).to(device)
        n_rows = xxtrain.shape[0]
        if reward_triplet_weight + imitation_triplet_weight > 0.0001:
            for i in range(n_rows):
                
                if imitation_triplet_weight > .0001:
                    imitation_tloss += get_tloss(i,0,ytrain,xxtrain,True)
                    imitation_tloss += get_tloss(i,1,ytrain,x1_imitation,True)
                    imitation_tloss += get_tloss(i,2,ytrain,x2_imitation,True)
                if reward_triplet_weight > .0001:
                    opt_tloss += get_tloss(i,0,y_opt,xxtrain,False)
                    opt_tloss += get_tloss(i,1,y_opt,opt_input2,False)
                    opt_tloss += get_tloss(i,2,y_opt,opt_input3,False)
            loss += torch.mul(imitation_tloss[0],imitation_triplet_weight/n_rows)
            loss += torch.mul(opt_tloss[0],reward_triplet_weight/n_rows)
        losses = [iloss,reward_loss,imitation_tloss*imitation_triplet_weight/n_rows,opt_tloss*reward_triplet_weight/n_rows]
        
        if train:
            loss.backward()
            optimizer.step()
            return losses
        else:
            scores = []
            distributions = [decision1_opt.mean().item(),decision2_opt.mean().item(),decision3_opt.mean().item()]
            imitation = [decision1_imitation,decision2_imitation,decision3_imitation]
            optimal = [decision1_opt,decision2_opt,decision3_opt]
            for i,decision_im in enumerate(imitation):
                deci = decision_im.cpu().detach().numpy()
                deci0 = (deci > .5).astype(int)
                iout = ytrain[:,i].cpu().detach().numpy()
                acci = accuracy_score(iout,deci0)
                try:
                    auci = roc_auc_score(iout,deci)
                except:
                    auci = -1
                
                deco = optimal[i].cpu().detach().numpy()
                deci0 = (deco > .5).astype(int)
                oout = y_opt[:,i].cpu().detach().numpy()
                acco = accuracy_score(oout,deci0)
                try:
                    auco = roc_auc_score(oout,deco)
                except:
                    auco=-1
                scores.append({'decision': i,'optimal_auc': auco,'imitation_auc': auci,'optimal_acc': acco,'imitation_acc': acci})
            return losses, scores, distributions
        
    best_val_loss = torch.tensor(1000000000.0)
    steps_since_improvement = 0
    best_val_score = {}
    
    for epoch in range(epochs):
        losses = step(True)
        val_losses,val_metrics,val_distributions = step(False)
        vl = val_losses[0] + val_losses[1]
        for vm in val_metrics:
            vl += (-((vm['optimal_auc']*reward_weight) + (vm['imitation_auc']*imitation_weight)))/10
        if verbose:
            print('______epoch',str(epoch),'_____')
            print('val reward',val_losses[1].item())
            print('imitation reward', val_losses[0].item())
            print('distance losses',val_losses[2].item(),val_losses[-1].item())
            print('distributions',val_distributions)
            print(val_metrics)
        if vl < best_val_loss:
            best_val_loss = vl
            best_val_score = val_metrics
            best_val_distributions = val_distributions
            steps_since_improvement = 0
            torch.save(model.state_dict(),save_file)
        else:
            steps_since_improvement += 1
        if steps_since_improvement > patience:
            break
    print('++++++++++Final+++++++++++')
    print('best',best_val_loss)
    print(best_val_score)
    model.load_state_dict(torch.load(save_file))
    model.eval()
    return model, best_val_score, best_val_loss, best_val_distributions

from Models import *
args = {
    'hidden_layers': [1000,1000], 
    'opt_layer_size': 20, 
    'imitation_layer_size': 20, 
    'dropout': 0.25, 
    'input_dropout': 0.1, 
    'shufflecol_chance': 0.5
}

#1.8424
# decision_model, decision_score, decision_loss, _ 
rad_results = train_decision_model_triplet(
    rad_model1,rad_model2,rad_model3,rad_smodel3,
    dataset = rad_data,
    lr=.01,
    imitation_weight=1,
    reward_weight=1,
    patience=100,
    imitation_triplet_weight=0,
    reward_triplet_weight =0, 
    verbose=True,
    weights=[1,1,1,1], #realtive weight of survival, feeding tube, aspiration, andl lrc
    tweights=[1,1,1,0], #weight for OS, LRC, FDM, and event (any + FT or AS at 6m) as time to event in weeks
    use_attention=True,
    **args)

rad_results[2]

tensor([79., 49.,  0.]) 389
tensor([23., 22.,  0.]) 147
torch.Size([3, 536, 94])
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 0 _____
val reward 1.4960142374038696
imitation reward 2.0263779163360596
distance losses 0.0 0.0
distributions [0.006183651741594076, 0.007560078054666519, 0.0007955669425427914]
[{'decision': 0, 'optimal_auc': 0.7289621318373072, 'imitation_auc': 0.6340648854961832, 'optimal_acc': 0.8435374149659864, 'imitation_acc': 0.891156462585034}, {'decision': 1, 'optimal_auc': 0.6880000000000001, 'imitation_auc': 0.6160326086956522, 'optimal_acc': 0.8503401360544217, 'imitation_acc': 0.782312925170068}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7736808645899556, 'optimal_acc': 1.0, 'imitation_acc': 0.8231292517006803}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 1 _____
val reward 1.0062206983566284
imitation reward 1.2641663551330566
distance losses 0.0 0.0
distributions [0.06562148779630661, 0.012886023148

tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 15 _____
val reward 0.45085421204566956
imitation reward 1.2133344411849976
distance losses 0.0 0.0
distributions [0.21227982640266418, 0.16402383148670197, 3.919087703252444e-07]
[{'decision': 0, 'optimal_auc': 0.841164095371669, 'imitation_auc': 0.5935114503816794, 'optimal_acc': 0.8707482993197279, 'imitation_acc': 0.8571428571428571}, {'decision': 1, 'optimal_auc': 0.9872727272727273, 'imitation_auc': 0.6608695652173913, 'optimal_acc': 0.9523809523809523, 'imitation_acc': 0.7755102040816326}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8184996821360458, 'optimal_acc': 1.0, 'imitation_acc': 0.8639455782312925}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 16 _____
val reward 0.4848196506500244
imitation reward 1.2575812339782715
distance losses 0.0 0.0
distributions [0.18979278206825256, 0.21251678466796875, 3.019082157607045e-07]
[{'decision': 0, 'optimal_auc': 0.841865357643758

tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 27 _____
val reward 0.49101492762565613
imitation reward 1.5292625427246094
distance losses 0.0 0.0
distributions [0.15132659673690796, 0.16662205755710602, 2.6552626763987064e-07]
[{'decision': 0, 'optimal_auc': 0.8373071528751753, 'imitation_auc': 0.5911259541984732, 'optimal_acc': 0.8843537414965986, 'imitation_acc': 0.8775510204081632}, {'decision': 1, 'optimal_auc': 0.993090909090909, 'imitation_auc': 0.6671195652173912, 'optimal_acc': 0.9523809523809523, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8140495867768596, 'optimal_acc': 1.0, 'imitation_acc': 0.8231292517006803}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 28 _____
val reward 0.5053893327713013
imitation reward 1.5667080879211426
distance losses 0.0 0.0
distributions [0.1822843849658966, 0.16037599742412567, 2.5695123895275174e-07]
[{'decision': 0, 'optimal_auc': 0.83590462833099

tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 39 _____
val reward 0.5694934129714966
imitation reward 2.10575795173645
distance losses 0.0 0.0
distributions [0.16536913812160492, 0.14255653321743011, 3.81949369909762e-08]
[{'decision': 0, 'optimal_auc': 0.8345021037868162, 'imitation_auc': 0.5481870229007634, 'optimal_acc': 0.8299319727891157, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.993090909090909, 'imitation_auc': 0.5997282608695652, 'optimal_acc': 0.9795918367346939, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8032422123331214, 'optimal_acc': 1.0, 'imitation_acc': 0.8095238095238095}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 40 _____
val reward 0.5703554749488831
imitation reward 2.2396161556243896
distance losses 0.0 0.0
distributions [0.16605646908283234, 0.14723193645477295, 2.4130708098368814e-08]
[{'decision': 0, 'optimal_auc': 0.8397615708274895, 

tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 51 _____
val reward 0.638163149356842
imitation reward 2.795691728591919
distance losses 0.0 0.0
distributions [0.1309516578912735, 0.17250226438045502, 9.361569297539063e-09]
[{'decision': 0, 'optimal_auc': 0.8394109396914446, 'imitation_auc': 0.5710877862595419, 'optimal_acc': 0.8435374149659864, 'imitation_acc': 0.8299319727891157}, {'decision': 1, 'optimal_auc': 0.9941818181818182, 'imitation_auc': 0.5679347826086957, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7937062937062938, 'optimal_acc': 1.0, 'imitation_acc': 0.7619047619047619}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 52 _____
val reward 0.6476528644561768
imitation reward 2.784614086151123
distance losses 0.0 0.0
distributions [0.1337180733680725, 0.17456646263599396, 9.30515664521181e-09]
[{'decision': 0, 'optimal_auc': 0.8380084151472651, 'im

tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 63 _____
val reward 0.6458596587181091
imitation reward 3.1445415019989014
distance losses 0.0 0.0
distributions [0.1642579436302185, 0.15304513275623322, 4.34343672139903e-09]
[{'decision': 0, 'optimal_auc': 0.8432678821879382, 'imitation_auc': 0.5825381679389313, 'optimal_acc': 0.8503401360544217, 'imitation_acc': 0.8435374149659864}, {'decision': 1, 'optimal_auc': 0.9952727272727273, 'imitation_auc': 0.5709239130434782, 'optimal_acc': 0.9863945578231292, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7835346471710108, 'optimal_acc': 1.0, 'imitation_acc': 0.8027210884353742}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 64 _____
val reward 0.6516125798225403
imitation reward 3.3115386962890625
distance losses 0.0 0.0
distributions [0.1482512354850769, 0.14171072840690613, 2.941488830288108e-09]
[{'decision': 0, 'optimal_auc': 0.8488779803646563, 

tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 75 _____
val reward 0.720704197883606
imitation reward 3.542299747467041
distance losses 0.0 0.0
distributions [0.1807674616575241, 0.15251590311527252, 3.163336925737781e-09]
[{'decision': 0, 'optimal_auc': 0.8520336605890603, 'imitation_auc': 0.6063931297709924, 'optimal_acc': 0.8503401360544217, 'imitation_acc': 0.8027210884353742}, {'decision': 1, 'optimal_auc': 0.990909090909091, 'imitation_auc': 0.5323369565217391, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7346938775510204}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.79815638906548, 'optimal_acc': 1.0, 'imitation_acc': 0.8027210884353742}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 76 _____
val reward 0.7052645087242126
imitation reward 3.527566432952881
distance losses 0.0 0.0
distributions [0.16785617172718048, 0.15682412683963776, 4.098939854202399e-09]
[{'decision': 0, 'optimal_auc': 0.8509817671809256, 'imi

tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 87 _____
val reward 0.6822590231895447
imitation reward 3.9738149642944336
distance losses 0.0 0.0
distributions [0.1546354740858078, 0.1583145558834076, 2.1564963148534844e-08]
[{'decision': 0, 'optimal_auc': 0.861500701262272, 'imitation_auc': 0.5825381679389313, 'optimal_acc': 0.8571428571428571, 'imitation_acc': 0.8639455782312925}, {'decision': 1, 'optimal_auc': 0.9945454545454545, 'imitation_auc': 0.5317934782608695, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8013350286077559, 'optimal_acc': 1.0, 'imitation_acc': 0.8027210884353742}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 88 _____
val reward 0.6778626441955566
imitation reward 4.047439098358154
distance losses 0.0 0.0
distributions [0.13786737620830536, 0.16136561334133148, 1.656859893728324e-08]
[{'decision': 0, 'optimal_auc': 0.8597475455820476, 

tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 99 _____
val reward 0.7418086528778076
imitation reward 3.5277793407440186
distance losses 0.0 0.0
distributions [0.15346616506576538, 0.17220622301101685, 1.9871528422754636e-08]
[{'decision': 0, 'optimal_auc': 0.8299438990182327, 'imitation_auc': 0.5384064885496183, 'optimal_acc': 0.8503401360544217, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.9949090909090909, 'imitation_auc': 0.579891304347826, 'optimal_acc': 0.9659863945578231, 'imitation_acc': 0.7278911564625851}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7930705657978385, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 100 _____
val reward 0.7561330795288086
imitation reward 3.5767195224761963
distance losses 0.0 0.0
distributions [0.151222825050354, 0.17450034618377686, 1.8732773554575033e-08]
[{'decision': 0, 'optimal_auc': 0.829242636746143

tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 111 _____
val reward 0.8404582738876343
imitation reward 3.668358325958252
distance losses 0.0 0.0
distributions [0.17303594946861267, 0.14564195275306702, 1.863332066420753e-08]
[{'decision': 0, 'optimal_auc': 0.8288920056100982, 'imitation_auc': 0.5491412213740459, 'optimal_acc': 0.8503401360544217, 'imitation_acc': 0.8299319727891157}, {'decision': 1, 'optimal_auc': 0.9905454545454545, 'imitation_auc': 0.5418478260869565, 'optimal_acc': 0.9523809523809523, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7937062937062938, 'optimal_acc': 1.0, 'imitation_acc': 0.8163265306122449}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 112 _____
val reward 0.84120112657547
imitation reward 3.6963701248168945
distance losses 0.0 0.0
distributions [0.17409701645374298, 0.14449159801006317, 1.5704861411336424e-08]
[{'decision': 0, 'optimal_auc': 0.829242636746143

/tmp/ipykernel_2619893/3871624404.py:355: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(save_file))


tensor(1.3371, grad_fn=<AddBackward0>)

In [26]:
pd.DataFrame(rad_results[1])

,decision,optimal_auc,imitation_auc,optimal_acc,imitation_acc
0,0,0.869215,0.588740,0.877551,0.891156
1,1,0.983636,0.651359,0.911565,0.734694
2,2,-1.000000,0.792117,1.000000,0.816327


In [33]:
control_results = train_decision_model_triplet(
    control_model1,control_model2,control_model3,control_smodel3,
    dataset=control_data,
    lr=.01,
    imitation_weight=1,
    reward_weight=1,
    patience=100,
    imitation_triplet_weight=0,
    reward_triplet_weight =0, 
    verbose=True,
    weights=[1,1,1,1], #realtive weight of survival, feeding tube, aspiration, andl lrc
    tweights=[1,1,1,0], #weight for OS, LRC, FDM, and event (any + FT or AS at 6m) as time to event in weeks
    use_attention=True,
    **args)

control_results[2]

tensor([246.,  91.,   0.]) 389
tensor([89., 37.,  0.]) 147
torch.Size([3, 536, 86])
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 0 _____
val reward 1.6990019083023071
imitation reward 2.0547354221343994
distance losses 0.0 0.0
distributions [0.7937368750572205, 0.014970784075558186, 0.001257091760635376]
[{'decision': 0, 'optimal_auc': 0.6381247578457963, 'imitation_auc': 0.6221374045801527, 'optimal_acc': 0.6054421768707483, 'imitation_acc': 0.891156462585034}, {'decision': 1, 'optimal_auc': 0.9422604422604424, 'imitation_auc': 0.6152173913043478, 'optimal_acc': 0.7482993197278912, 'imitation_acc': 0.782312925170068}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7848061029879212, 'optimal_acc': 1.0, 'imitation_acc': 0.8231292517006803}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 1 _____
val reward 1.4893807172775269
imitation reward 1.6024320125579834
distance losses 0.0 0.0
distributions [0.16329051554203033, 0.243764936923

tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 15 _____
val reward 0.8132466673851013
imitation reward 1.161198377609253
distance losses 0.0 0.0
distributions [0.7040612101554871, 0.2935412526130676, 3.113297225354472e-06]
[{'decision': 0, 'optimal_auc': 0.6906237892289809, 'imitation_auc': 0.5672709923664122, 'optimal_acc': 0.6530612244897959, 'imitation_acc': 0.8299319727891157}, {'decision': 1, 'optimal_auc': 0.9955773955773957, 'imitation_auc': 0.6866847826086957, 'optimal_acc': 0.9455782312925171, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8442466624284806, 'optimal_acc': 1.0, 'imitation_acc': 0.8299319727891157}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 16 _____
val reward 0.7766740918159485
imitation reward 1.1652536392211914
distance losses 0.0 0.0
distributions [0.6727835536003113, 0.2819080352783203, 2.6047507617477095e-06]
[{'decision': 0, 'optimal_auc': 0.7068965517241379, '

tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 27 _____
val reward 0.9487404227256775
imitation reward 1.509016752243042
distance losses 0.0 0.0
distributions [0.6279917359352112, 0.3062254786491394, 1.1648319286905462e-06]
[{'decision': 0, 'optimal_auc': 0.7415730337078652, 'imitation_auc': 0.545324427480916, 'optimal_acc': 0.6802721088435374, 'imitation_acc': 0.8571428571428571}, {'decision': 1, 'optimal_auc': 0.990909090909091, 'imitation_auc': 0.6929347826086956, 'optimal_acc': 0.9251700680272109, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7768595041322314, 'optimal_acc': 1.0, 'imitation_acc': 0.782312925170068}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 28 _____
val reward 1.0042864084243774
imitation reward 1.538038730621338
distance losses 0.0 0.0
distributions [0.6143869757652283, 0.314139187335968, 1.2826579904867685e-06]
[{'decision': 0, 'optimal_auc': 0.738860906625339, 'imita

tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 39 _____
val reward 1.1484229564666748
imitation reward 2.0849130153656006
distance losses 0.0 0.0
distributions [0.6437362432479858, 0.2862473428249359, 2.621891894705186e-07]
[{'decision': 0, 'optimal_auc': 0.7692754746222394, 'imitation_auc': 0.5696564885496184, 'optimal_acc': 0.7074829931972789, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9874692874692875, 'imitation_auc': 0.6331521739130435, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7066115702479339, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 40 _____
val reward 1.1743073463439941
imitation reward 2.1874125003814697
distance losses 0.0 0.0
distributions [0.6391404867172241, 0.2902525067329407, 2.3822168770948338e-07]
[{'decision': 0, 'optimal_auc': 0.7739248353351414, 

tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 51 _____
val reward 1.305857539176941
imitation reward 2.368690013885498
distance losses 0.0 0.0
distributions [0.6201431155204773, 0.2831052243709564, 1.94479909509937e-07]
[{'decision': 0, 'optimal_auc': 0.7512592018597444, 'imitation_auc': 0.5620229007633588, 'optimal_acc': 0.6802721088435374, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.990909090909091, 'imitation_auc': 0.6711956521739131, 'optimal_acc': 0.9455782312925171, 'imitation_acc': 0.7755102040816326}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6951684678957406, 'optimal_acc': 1.0, 'imitation_acc': 0.782312925170068}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 52 _____
val reward 1.2856413125991821
imitation reward 2.4572396278381348
distance losses 0.0 0.0
distributions [0.576102614402771, 0.2761238217353821, 1.7593909262814122e-07]
[{'decision': 0, 'optimal_auc': 0.7584269662921348, 'imita

tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 63 _____
val reward 1.4883979558944702
imitation reward 2.7327513694763184
distance losses 0.0 0.0
distributions [0.603850781917572, 0.2844223380088806, 4.1530537941980583e-07]
[{'decision': 0, 'optimal_auc': 0.7115459124370399, 'imitation_auc': 0.5844465648854962, 'optimal_acc': 0.673469387755102, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9869778869778869, 'imitation_auc': 0.6682065217391304, 'optimal_acc': 0.9319727891156463, 'imitation_acc': 0.782312925170068}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7043865225683408, 'optimal_acc': 1.0, 'imitation_acc': 0.782312925170068}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 64 _____
val reward 1.494387149810791
imitation reward 2.7553038597106934
distance losses 0.0 0.0
distributions [0.5729195475578308, 0.2981221079826355, 5.460863121697912e-07]
[{'decision': 0, 'optimal_auc': 0.7171638899651298, 'imit

tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 75 _____
val reward 1.5381505489349365
imitation reward 2.865497589111328
distance losses 0.0 0.0
distributions [0.6328425407409668, 0.3005111515522003, 2.379083667847226e-07]
[{'decision': 0, 'optimal_auc': 0.7415730337078652, 'imitation_auc': 0.5777671755725191, 'optimal_acc': 0.7006802721088435, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9891891891891892, 'imitation_auc': 0.6489130434782608, 'optimal_acc': 0.9319727891156463, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.705022250476796, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 76 _____
val reward 1.5160620212554932
imitation reward 2.9294488430023193
distance losses 0.0 0.0
distributions [0.6152823567390442, 0.29463738203048706, 2.769369871202798e-07]
[{'decision': 0, 'optimal_auc': 0.743510267338241, 'im

tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 87 _____
val reward 1.5686683654785156
imitation reward 3.137742042541504
distance losses 0.0 0.0
distributions [0.6077306270599365, 0.2819221019744873, 1.5174726968325558e-06]
[{'decision': 0, 'optimal_auc': 0.725881441301821, 'imitation_auc': 0.5832538167938931, 'optimal_acc': 0.7006802721088435, 'imitation_acc': 0.8367346938775511}, {'decision': 1, 'optimal_auc': 0.9835380835380836, 'imitation_auc': 0.6323369565217392, 'optimal_acc': 0.9455782312925171, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6710108073744437, 'optimal_acc': 1.0, 'imitation_acc': 0.7482993197278912}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 88 _____
val reward 1.620465636253357
imitation reward 3.2027993202209473
distance losses 0.0 0.0
distributions [0.629379391670227, 0.2838924825191498, 1.3655858310812619e-06]
[{'decision': 0, 'optimal_auc': 0.725009686168152, 'imi

tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 99 _____
val reward 1.7269372940063477
imitation reward 3.082510471343994
distance losses 0.0 0.0
distributions [0.6284551620483398, 0.30066436529159546, 1.6690353277226677e-06]
[{'decision': 0, 'optimal_auc': 0.7237504843084076, 'imitation_auc': 0.5634541984732825, 'optimal_acc': 0.6598639455782312, 'imitation_acc': 0.8095238095238095}, {'decision': 1, 'optimal_auc': 0.9842751842751843, 'imitation_auc': 0.6516304347826086, 'optimal_acc': 0.9455782312925171, 'imitation_acc': 0.7346938775510204}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.677050222504768, 'optimal_acc': 1.0, 'imitation_acc': 0.7687074829931972}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 100 _____
val reward 1.7080286741256714
imitation reward 3.147000312805176
distance losses 0.0 0.0
distributions [0.6168451905250549, 0.30266278982162476, 1.2882969713245984e-06]
[{'decision': 0, 'optimal_auc': 0.7260751646648587,

/tmp/ipykernel_2619893/3871624404.py:355: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(save_file))


tensor(1.5041, grad_fn=<AddBackward0>)

In [35]:
pd.DataFrame(rad_results[1]).set_index('decision') - pd.DataFrame(control_results[1]).set_index('decision')

,optimal_auc,imitation_auc,optimal_acc,imitation_acc
decision,,,,
0,0.122191,0.023855,0.210884,0.000000
1,-0.015479,-0.037500,-0.006803,0.013605
2,0.000000,-0.028926,0.000000,0.006803


In [ ]:
pd.DataFrame(control_results[1])

In [38]:
rad_decision_model = rad_results[0]
rad_decision_model.set_device('cpu')
torch.save(rad_decision_model,'../resources/radcluster_decision_model.pt')
pd.DataFrame(rad_results[1]).to_csv('../results/radcluster_policy_model_score.csv')
rad_decision_model

DecisionAttentionModel(
  (input_dropout): Dropout(p=0.1, inplace=False)
  (layers): ModuleList(
    (0): Linear(in_features=100, out_features=1000, bias=True)
  )
  (batchnorm): BatchNorm1d(1000, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (dropout): Dropout(p=0.25, inplace=False)
  (relu): Softplus(beta=1.0, threshold=20.0)
  (sigmoid): Sigmoid()
  (softmax): Softmax(dim=1)
  (final_opt_layer): Linear(in_features=1000, out_features=100, bias=True)
  (final_imitation_layer): Linear(in_features=1000, out_features=100, bias=True)
  (final_layer): Linear(in_features=1000, out_features=6, bias=True)
  (resize_layer): Linear(in_features=98, out_features=100, bias=True)
  (attentions): ModuleList(
    (0): MultiheadAttention(
      (out_proj): NonDynamicallyQuantizableLinear(in_features=100, out_features=100, bias=True)
    )
  )
  (norms): ModuleList(
    (0): LayerNorm((100,), eps=1e-05, elementwise_affine=True)
  )
  (activation): ReLU()
)